// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZp9wOBaLEK15rfr0PEoWo8hdKMjWKXc4',
    appId: '1:176492539093:android:26a220e733e681879bc65c',
    messagingSenderId: '176492539093',
    projectId: 'chat-app-35ca1',
    storageBucket: 'chat-app-35ca1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3gaPZyhPwIvEcvhetRdhAq4KjhIF0R_o',
    appId: '1:176492539093:ios:c0033bb064f0fe749bc65c',
    messagingSenderId: '176492539093',
    projectId: 'chat-app-35ca1',
    storageBucket: 'chat-app-35ca1.appspot.com',
    androidClientId: '176492539093-vjm4v26rh21orvr25hj30c9ikvc27uld.apps.googleusercontent.com',
    iosClientId: '176492539093-dlgs92eqba113k58dln572kj6fctseoa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}